<a href="https://colab.research.google.com/github/haran2248/nhanes_study/blob/meta_data/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:

from google.colab import files
uploaded = files.upload()
import io
import pandas as pd
df1 = pd.read_csv(io.BytesIO(uploaded['Nhanes1.csv']))
display(df1)

         SEQN  SDDSRVYR  ...  HEI2015C13_ADDSUG_2  HEI2015_TOTAL_SCORE_2
0      100000        10  ...                 10.0                    NaN
1      100000        10  ...                 10.0                    NaN
2      100000        10  ...                 10.0                    NaN
3      100000        10  ...                 10.0                    NaN
4      100000        10  ...                 10.0                    NaN
...       ...       ...  ...                  ...                    ...
50163   84759         9  ...                 10.0              86.619515
50164   84759         9  ...                 10.0              86.619515
50165   84759         9  ...                 10.0              86.619515
50166   84759         9  ...                 10.0              86.619515
50167   84759         9  ...                 10.0              86.619515

[50168 rows x 737 columns]